sonar.organization=ajitirto
sonar.projectKey=ajitirto_sonarqube-go
sonar.projectName=sonarqube-go

# Path ke kode sumber
sonar.sources=.
sonar.exclusions=**/*_test.go

# Path ke berkas pengujian dan coverage
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
